# Generated by Django 3.2.15 on 2022-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email', models.EmailField(default='user@domain.com', max_length=254)),
                ('posting_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
