# Generated by Django 3.2.15 on 2022-12-18 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(blank=True, default='anonym', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, default='user@domain.com', max_length=254, unique=True),
        ),
    ]
