# Generated by Django 3.2.15 on 2022-12-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(default='user@domain.com', max_length=254),
        ),
    ]
